# frozen_string_literal: true

source "https://rubygems.org"
ruby '2.3.4'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "vault", "~> 0.11"

group :test do
  gem 'rake'
  gem 'rspec'
end
